// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZOvWJxEMqv1EQpsEWb74KGuzuc6ist8',
    appId: '1:948759682137:web:1d2e9bb9fdbe615e6da548',
    messagingSenderId: '948759682137',
    projectId: 'masrofy-918',
    authDomain: 'masrofy-918.firebaseapp.com',
    storageBucket: 'masrofy-918.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVA1xK1s97e8kYzZ1bh40EHC8qbQKe4lM',
    appId: '1:948759682137:android:721df751414ad9606da548',
    messagingSenderId: '948759682137',
    projectId: 'masrofy-918',
    storageBucket: 'masrofy-918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbREVpqzTTmetF3OpkpQc0gLiu8MmwXY',
    appId: '1:948759682137:ios:79b53fff222a5ba96da548',
    messagingSenderId: '948759682137',
    projectId: 'masrofy-918',
    storageBucket: 'masrofy-918.firebasestorage.app',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLbREVpqzTTmetF3OpkpQc0gLiu8MmwXY',
    appId: '1:948759682137:ios:79b53fff222a5ba96da548',
    messagingSenderId: '948759682137',
    projectId: 'masrofy-918',
    storageBucket: 'masrofy-918.firebasestorage.app',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzZOvWJxEMqv1EQpsEWb74KGuzuc6ist8',
    appId: '1:948759682137:web:39f4284fb01715b26da548',
    messagingSenderId: '948759682137',
    projectId: 'masrofy-918',
    authDomain: 'masrofy-918.firebaseapp.com',
    storageBucket: 'masrofy-918.firebasestorage.app',
  );
}
